apiVersion: skaffold/v4beta12
kind: Config
build:
    artifacts:
        - image: jamalalhneidi/auth
          context: auth
          sync:
              manual:
                  - src: src/**/*.ts
                    dest: .
          docker:
              dockerfile: Dockerfile
        - image: jamalalhneidi/client
          context: client
          sync:
              manual:
                  - src: '**/*.js'
                    dest: .
          docker:
              dockerfile: Dockerfile
        - image: jamalalhneidi/tickets
          context: tickets
          sync:
              manual:
                  - src: src/**/*.js
                    dest: .
          docker:
              dockerfile: Dockerfile
        - image: jamalalhneidi/orders
          context: orders
          sync:
              manual:
                  - src: src/**/*.js
                    dest: .
          docker:
              dockerfile: Dockerfile
        - image: jamalalhneidi/expiration
          context: expiration
          sync:
              manual:
                  - src: src/**/*.js
                    dest: .
          docker:
              dockerfile: Dockerfile
        - image: jamalalhneidi/payments
          context: payments
          sync:
              manual:
                  - src: src/**/*.js
                    dest: .
          docker:
              dockerfile: Dockerfile
    local:
        push: false
manifests:
    rawYaml:
        - infra/k8s/*
deploy:
    kubectl: {}
