name: deploy-%name

on:
    push:
        branches:
            - main
        paths:
            - '%name/**'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: cd %name && docker build -t jamalalhneidi/%name .
            - run: docker login -u $DOCKER_USERNAME -p DOCKER_PASSWORD
              env:
                  key:
                      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
                      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
            - run: docker push jamalalhneidi/%name
