name: test-%name

on:
    pull_request:
        paths:
            - '%name/**'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: cd %name && npm i && npm run test:ci
