name: deploy-tickets

on:
    push:
        branches:
            - main
        paths:
            - 'tickets/**'

jobs:
    login:
        runs-on: ubuntu-latest
        steps:
            - name: Login to Docker Hub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - uses: actions/checkout@v2
            - run: cd tickets && docker build -t jamalalhneidi/tickets .
            - run: docker push jamalalhneidi/tickets
