name: deploy-client

on:
    push:
        branches:
            - main
        paths:
            - 'client/**'

jobs:
    login:
        runs-on: ubuntu-latest
        steps:
            - name: Login to Docker Hub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: cd client && docker build -t jamalalhneidi/client .
            - run: docker push jamalalhneidi/client
