name: deploy-common

on:
    push:
        branches:
            - main
        paths:
            - 'common/**'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: cd common && docker build -t jamalalhneidi/common .
            - run: docker login -u $DOCKER_USERNAME -p DOCKER_PASSWORD
              env:
                  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
                  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
            - run: docker push jamalalhneidi/common
