name: deploy-auth

on:
    push:
        branches:
            - main
        paths:
            - 'auth/**'

jobs:
    login:
        runs-on: ubuntu-latest
        steps:
            - name: Login to Docker Hub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: cd auth && docker build -t jamalalhneidi/auth .
            - run: docker push jamalalhneidi/auth
