name: deploy-common

on:
    push:
        branches:
            - main
        paths:
            - 'common/**'

jobs:
    login:
        runs-on: ubuntu-latest
        steps:
            - name: Login to Docker Hub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - uses: actions/checkout@v2
            - run: cd common && docker build -t jamalalhneidi/common .
            - run: docker push jamalalhneidi/common
